name: Release AmneziaWG Kernel Module
on: [workflow_dispatch]
# on:
#   push:
#     tags:
#       - "v*.*.*"

jobs:
  build:
    name: "${{ matrix.tag }} - ${{ matrix.build_env.pkgarch}} :: ${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}} build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['v23.05.0']
        build_env:
          - pkgarch: mipsel_24kc
            target: ramips
            subtarget: mt7621
    steps:
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: ${{ matrix.tag }}
          fetch-depth: 0

      - name: Cache Tools and Kernel
        id: cache-tools-kernel
        uses: actions/cache@v3
        env:
          cache-name: "cache-tools-kernel-${{ matrix.tag }}-${{ matrix.build_env.pkgarch}}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}"
        with:
          path: .
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Building kernel and tools
        if: ${{ steps.cache-tools-kernel.outputs.cache-hit != 'true' }}
        run: |
          pkgarch=${{ matrix.build_env.pkgarch}}
          target=${{ matrix.build_env.target}}
          subtarget=${{ matrix.build_env.subtarget}}

          echo "pkgarch: ${pkgarch}, target: ${target}, subtarget: ${subtarget}"

          echo "CONFIG_TARGET_${target}=y" > .config
          echo "CONFIG_TARGET_${target}_${subtarget}=y" >> .config
          echo "CONFIG_DEFAULT_TARGET_${target}_${subtarget}=y" >> .config
          echo "CONFIG_ALL_KMODS=y" >> .config

          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_kmod-crypto-lib-chacha20=m" >> .config
          echo "CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=m" >> .config
          echo "CONFIG_PACKAGE_kmod-crypto-chacha20poly1305=m" >> .config

          make defconfig

          echo "    > make tools/install"
          make tools/install
          echo "    > make toolchain/install"
          make toolchain/install
          # compile kernel module
          echo "    > make target/linux/compile"
          make target/linux/compile V=s

      - name: Building AmneziaWG
        run: |
          echo "CONFIG_PACKAGE_amnezia-wg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config
          make defconfig

          # fixing feed
          echo "src-git packages https://git.openwrt.org/feed/packages.git^0da9f622975aa1e4efe452da4acbae15479bee63" > ./feeds.conf.default
          echo "src-git luci https://git.openwrt.org/project/luci.git^257f54cb8bcd493d9be0a45a3c316668b793e8ae" >> ./feeds.conf.default
          echo "src-git routing https://git.openwrt.org/feed/routing.git^2272106e0839ee06957e88e3596489e1b510d3c2" >> ./feeds.conf.default
          echo "src-git telephony https://git.openwrt.org/feed/telephony.git^9746ae8f964e18f04b64fbe1956366954ff223f8" >> ./feeds.conf.default
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> ./feeds.conf.default

          ./scripts/feeds update luci
          ./scripts/feeds install -a -p luci
          ./scripts/feeds update awgopenwrt
          ./scripts/feeds install -a -p awgopenwrt

          make package/amnezia-wg-tools/{clean,download,prepare}
          make package/luci-app-amneziawg/{clean,download,prepare}
          make package/kmod-amneziawg/{clean,download,prepare}

          make package/amnezia-wg-tools/compile
          make package/luci-app-amneziawg/compile V=s
          make package/kmod-amneziawg/compile

      - name: LS Packages
        run: |
          ls -al bin/packages/${{ matrix.build_env.pkgarch }}/awgopenwrt
          ls -al bin/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/packages/

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       bin/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/packages/kmod-amneziawg*.ipk
